# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '21b469cb-ea9a-4524-b2d4-d45392f52c7f'
  webappimageRepository: 'azuredevopsqnawebapp'
  batchprocessimageRepository: 'azuredevopsqnabatchprocess'
  containerRegistry: 'mlsandboxreg.azurecr.io'
  webappDockerfilePath: 'WebApp.Dockerfile'
  batchprocessDockerfilePath: 'BatchProcess.Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: WebAppBuild
    displayName: Build WebApp Container
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push WebApp image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(webappDockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          v1.0.0
  - job: BatchProcessBuild
    displayName: Build Batch Processing Container
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push Batch Processing image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(batchprocessDockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          v1.0.0

